import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {query,days,readApi,readExcel} from '../servicios/datos.mjs';
async function fixture(t){const dir=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../temporal');await fs.mkdir(dir,{recursive:true});const root=await fs.mkdtemp(path.join(dir,'capa-datos-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));return root;}
async function put(root,day,rows,events=[]){for(const [kind,value]of [['movimientos',rows],['truckflow',{records:events}]]){const dir=path.join(root,'data',kind,day);await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,kind==='movimientos'?'movimientos.json':'event-list.json'),JSON.stringify(value));}}
const op=(product,id='a')=>({external_operation_id:id,product_normalized:product,plate_normalized:'ABC123',planta_normalized:'RICARDONE',movement_type_detail:'I',external_ingreso_at:'2026-09-24T10:00:00',external_salida_at:'2026-09-24T12:00:00'});
test('grain exclusion, dedup provenance and distinct operation legs',async t=>{const root=await fixture(t);await put(root,'2026-09-24',[op('SOJA'),op('ACEITE SOJA'),op('PELLET SOJA'),{...op('SOJA'),movement_type_detail:'E'}]);await put(root,'2026-09-25',[op('SOJA')]);const r=await query({root,from:'2026-09-24',to:'2026-09-25',product:'SOJA'});assert.equal(r.denominators.movimientos,2);assert.equal(r.operations[0].evidence.length,2);assert.equal(r.denominators.patentesUnicas,1);});
test('missing day must not become zero confirmed activity',async t=>{const root=await fixture(t);await put(root,'2026-09-24',[]);assert.equal((await query({root,from:'2026-09-24',to:'2026-09-25',product:'SOJA'})).state,'DATOS_INSUFICIENTES');assert.equal((await query({root,from:'2026-09-24',to:'2026-09-24',product:'SOJA'})).state,'SIN_ACTIVIDAD_CONFIRMADA');});
test('camera candidate respects temporal evidence and flags journey ambiguity',async t=>{const root=await fixture(t);await put(root,'2026-09-24',[op('GIRASOL')],[{id:1,truckPlate:'ABC123',journeyUid:'j1',occurredAt:'2026-09-24T10:30:00-03:00'},{id:2,truckPlate:'ABC123',journeyUid:'j2',occurredAt:'2026-09-24T11:30:00-03:00'},{id:3,truckPlate:'ABC123',journeyUid:'j3',occurredAt:'2026-09-24T15:00:00-03:00'}]);const r=await query({root,from:'2026-09-24',to:'2026-09-24',product:'GIRASOL',plate:'ABC123'});assert.equal(r.operations[0].cameraEvidence.state,'AMBIGUO');assert.equal(r.operations[0].cameraEvidence.candidateEvents,2);assert.equal(r.events.length,3);});
test('invalid calendar and external API blocked',async()=>{assert.throws(()=>days('2026-02-30','2026-03-01'));await assert.rejects(readApi({path:'/x',base:'https://example.com'}));await assert.rejects(readApi({path:'http://example.com',base:'http://localhost:8787'}));});
test('Excel reader rejects outside repository',async t=>{const root=await fixture(t);await assert.rejects(readExcel({root,file:path.resolve(root,'..','outside.xlsx')}));});
test('timestamps originales con offset, inválidos y cámaras faltantes',async t=>{const root=await fixture(t);await put(root,'2026-09-24',[{...op('SOJA'),external_ingreso_at:'2026-09-24T10:00:00-03:00',external_salida_at:'2026-09-24T12:00:00-03:00'}],[{id:1,truckPlate:'ABC123',journeyUid:'j1',occurredAt:'2026-09-24T14:00:00Z'}]);let r=await query({root,from:'2026-09-24',to:'2026-09-24',product:'SOJA'});assert.equal(r.operations[0].cameraEvidence.candidateEvents,1);await assert.rejects(query({root,from:'2026-09-24',to:'2026-09-24',timestamps:{from:'wrong',to:'wrong'}}));await fs.unlink(path.join(root,'data/truckflow/2026-09-24/event-list.json'));r=await query({root,from:'2026-09-24',to:'2026-09-24',product:'SOJA'});assert.equal(r.operations[0].cameraEvidence.state,'DATOS_INSUFICIENTES');});
test('liquid taxonomy and operations-only adapter',async t=>{const {operations}=await import('../servicios/datos.mjs');const root=await fixture(t);await put(root,'2026-09-24',['BORRAS','GOMA','METANOL','METILATO','ACIDO GRASO','BIODIESEL','PELLET SOJA'].map((p,i)=>op(p,String(i))));const r=await operations({root,from:'2026-09-24',to:'2026-09-24',product:'LIQUIDOS'});assert.equal(r.denominators.movimientos,6);assert.equal(r.sources.length,1);});
test('run reader rejects prohibited tables/traversal and preserves metadata',async t=>{const {runTable}=await import('../servicios/datos.mjs');const root=await fixture(t);const dir=path.join(root,'runs/windows/2026-09-21_2026-09-27');await fs.mkdir(path.join(dir,'tables'),{recursive:true});await fs.writeFile(path.join(dir,'manifest.json'),JSON.stringify({runId:'2026-09-21_2026-09-27',rulesVersion:'fixture'}));await fs.writeFile(path.join(dir,'tables/excel_operations_with_truckflow.json'),JSON.stringify({rows:[{source_date:'2026-09-24'},{source_date:'2026-09-25'}]}));const r=await runTable({root,run:'2026-09-21_2026-09-27',table:'excel_operations_with_truckflow',from:'2026-09-24',to:'2026-09-24'});assert.equal(r.totalRows,1);assert.equal(r.rulesVersion,'fixture');await assert.rejects(runTable({root,run:'2026-09-21_2026-09-27',table:'merged_truckflow_movimientos'}));await assert.rejects(runTable({root,run:'2026-09-21_2026-09-27',table:'../manifest'}));});
test('placeholder mantiene movimiento pero no vehículo único ni vínculo cámara',async t=>{const root=await fixture(t);await put(root,'2026-09-24',[{...op('SOJA','p1'),plate_normalized:'TTTTTT'},{...op('SOJA','p2'),plate_normalized:'AAAA'},op('SOJA','p3')],[{id:1,truckPlate:'TTTTTT',journeyUid:'j',occurredAt:'2026-09-24T11:00:00-03:00'}]);const r=await query({root,from:'2026-09-24',to:'2026-09-24',product:'SOJA'});assert.equal(r.denominators.movimientos,3);assert.equal(r.denominators.patentesUnicas,1);assert.equal(r.denominators.movimientosSinPatenteUtilizable,2);assert.equal(r.operations[0].cameraEvidence.state,'DATOS_INSUFICIENTES');assert.equal(r.operations[0].cameraEvidence.candidateEvents,0);});
test('pellet wrapper rechaza corridas inseguras o período sin cobertura',async()=>{const {pellet}=await import('../servicios/pellet.mjs');await assert.rejects(pellet({from:'2026-09-24',to:'2026-09-30',runs:['../unsafe']}));await assert.rejects(pellet({from:'2026-09-24',to:'2026-09-30',runs:['2026-09-21_2026-09-27']}));});
